# Generated by Django 3.0.6 on 2020-05-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('description', models.TextField()),
                ('rate', models.IntegerField(max_length=3)),
                ('year', models.DateField()),
                ('editorial', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='books')),
                ('book_cover', models.ImageField(upload_to='books')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='categories.Category')),
            ],
        ),
    ]
