# Generated by Django 3.0.6 on 2020-05-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200514_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_home',
            field=models.BooleanField(default=False),
        ),
    ]
